/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.sql.SQLException;
import static java.sql.Types.NULL;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modele.ModeleJListEvenement;
import modele.ModeleJListPays;
import modele.ModeleJTableEvenementTotal;
import modele.ModeleJTableMariage;
import modele.ModeleJTableVIPL;
import modele.ModeleJTableVIP;
import tables.Evenement;
import tables.VIP;

/**
 *
 * @author Alice
 */
public class AccueilApplication extends javax.swing.JFrame {

    private ModeleJTableVIP leModeleVIP;
    private ModeleJListPays leModelePays;
    private ModeleJTableVIPL leModeleVIPL;
    private ModeleJListEvenement leModeleEvenement;
    private ModeleJTableMariage leModeleMariage;
    private ModeleJTableEvenementTotal leModeleEvenementTotal;
    
    private VIP vip = new VIP();
    private Evenement evenement = new Evenement();
    
    // variables de date
    Date date = new Date();
    Calendar cal = new GregorianCalendar();

    /**
     * Creates new form AccueilApplication
     */
    public AccueilApplication() throws SQLException {
        // instanciation du modèle de données de la JTable (liste des VIP)
        this.leModeleVIP = new ModeleJTableVIP();
        this.leModelePays = new ModeleJListPays();
        this.leModeleVIPL = new ModeleJTableVIPL();
        this.leModeleEvenement = new ModeleJListEvenement();
        this.leModeleMariage = new ModeleJTableMariage();
        this.leModeleEvenementTotal = new ModeleJTableEvenementTotal();
        
        
        try {
            leModeleVIP.chargerLesVIP();
            leModeleMariage.chargerLesMariages();
            leModeleEvenementTotal.chargerLesEvenementsTotal();
            initComponents();
        } catch (SQLException ex) {
            System.out.println("Erreur au chargement : " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCivilite = new javax.swing.ButtonGroup();
        buttonGroupRole = new javax.swing.ButtonGroup();
        buttonGroupStatut = new javax.swing.ButtonGroup();
        panConsulterLesEvenements = new javax.swing.JTabbedPane();
        panAjouterVIP = new javax.swing.JPanel();
        informationsVIP = new javax.swing.JPanel();
        lbNom = new javax.swing.JLabel();
        lbPrenom = new javax.swing.JLabel();
        lbCivilite = new javax.swing.JLabel();
        lbDateNaissance = new javax.swing.JLabel();
        lbLieuNaissance = new javax.swing.JLabel();
        lbRole = new javax.swing.JLabel();
        lbStatut = new javax.swing.JLabel();
        lbPays = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        rdM = new javax.swing.JRadioButton();
        rdMme = new javax.swing.JRadioButton();
        txtDateNaissance = new javax.swing.JTextField();
        txtLieuNaissance = new javax.swing.JTextField();
        rdLibre = new javax.swing.JRadioButton();
        rdOccupe = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPays = new javax.swing.JList<>();
        btValiderVIP = new javax.swing.JButton();
        btAnnulerVIP = new javax.swing.JButton();
        chkActeur = new javax.swing.JCheckBox();
        chkRealisateur = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panAjouterMariage = new javax.swing.JPanel();
        panAjoutMariage = new javax.swing.JPanel();
        lbSelectionVIP1 = new javax.swing.JLabel();
        lbConjoint = new javax.swing.JLabel();
        btnValiderMariage = new javax.swing.JButton();
        btnAnnulerMariage = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableConjoint = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableVIP1 = new javax.swing.JTable();
        txtDateMariage = new javax.swing.JTextField();
        txtLieuMariage = new javax.swing.JTextField();
        lbDateMariage = new javax.swing.JLabel();
        lbLieuMariage = new javax.swing.JLabel();
        btnActualiserVIPL = new javax.swing.JButton();
        panAjouterDivorce = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMariages = new javax.swing.JTable();
        lbSelectionnerMariage = new javax.swing.JLabel();
        btnValiderDivorce = new javax.swing.JToggleButton();
        btnAnnulerDivorce = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        txtDateDivorce = new javax.swing.JTextField();
        btnActualiserMariages = new javax.swing.JButton();
        panAjouterPhoto = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        lbBienvenue = new javax.swing.JLabel();
        lbLogin = new javax.swing.JLabel();
        btnDeconnexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panConsulterLesEvenements.setBackground(new java.awt.Color(255, 255, 255));

        panAjouterVIP.setBackground(new java.awt.Color(255, 255, 255));

        informationsVIP.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations VIP"));

        lbNom.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lbNom.setText("Nom");

        lbPrenom.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lbPrenom.setText("Prénom");

        lbCivilite.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lbCivilite.setText("Civilité");

        lbDateNaissance.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lbDateNaissance.setText("Date de naissance");

        lbLieuNaissance.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lbLieuNaissance.setText("Lieu de naissance");

        lbRole.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lbRole.setText("Role");

        lbStatut.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lbStatut.setText("Statut");

        lbPays.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lbPays.setText("Pays");

        buttonGroupCivilite.add(rdM);
        rdM.setSelected(true);
        rdM.setText("M.");

        buttonGroupCivilite.add(rdMme);
        rdMme.setText("Mme");

        buttonGroupStatut.add(rdLibre);
        rdLibre.setSelected(true);
        rdLibre.setText("Libre");

        buttonGroupStatut.add(rdOccupe);
        rdOccupe.setText("Occupé");

        listPays.setModel(leModelePays);
        listPays.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listPays.setToolTipText("");
        jScrollPane2.setViewportView(listPays);

        btValiderVIP.setText("Valider");
        btValiderVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderVIPActionPerformed(evt);
            }
        });

        btAnnulerVIP.setText("Annuler");
        btAnnulerVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerVIPActionPerformed(evt);
            }
        });

        chkActeur.setText("Acteur/trice");

        chkRealisateur.setText("Réalisateur/trice");

        javax.swing.GroupLayout informationsVIPLayout = new javax.swing.GroupLayout(informationsVIP);
        informationsVIP.setLayout(informationsVIPLayout);
        informationsVIPLayout.setHorizontalGroup(
            informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationsVIPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRole)
                    .addComponent(lbNom)
                    .addComponent(lbPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCivilite)
                    .addComponent(lbDateNaissance)
                    .addComponent(lbLieuNaissance)
                    .addComponent(lbStatut)
                    .addComponent(lbPays)
                    .addComponent(btValiderVIP, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informationsVIPLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btAnnulerVIP)
                        .addContainerGap())
                    .addGroup(informationsVIPLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(informationsVIPLayout.createSequentialGroup()
                                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(informationsVIPLayout.createSequentialGroup()
                                        .addComponent(rdM, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdMme, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(informationsVIPLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLieuNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informationsVIPLayout.createSequentialGroup()
                                                .addComponent(rdOccupe)
                                                .addGap(44, 44, 44)))))
                                .addContainerGap(28, Short.MAX_VALUE))
                            .addGroup(informationsVIPLayout.createSequentialGroup()
                                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdLibre, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(informationsVIPLayout.createSequentialGroup()
                                        .addComponent(chkActeur)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkRealisateur)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        informationsVIPLayout.setVerticalGroup(
            informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationsVIPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNom)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrenom)
                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCivilite)
                    .addComponent(rdM)
                    .addComponent(rdMme))
                .addGap(5, 5, 5)
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDateNaissance)
                    .addComponent(txtDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLieuNaissance)
                    .addComponent(txtLieuNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRole)
                    .addComponent(chkActeur)
                    .addComponent(chkRealisateur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStatut)
                    .addComponent(rdLibre)
                    .addComponent(rdOccupe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPays)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btValiderVIP)
                    .addComponent(btAnnulerVIP))
                .addContainerGap())
        );

        jTable1.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jTable1.setModel(leModeleVIP);
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout panAjouterVIPLayout = new javax.swing.GroupLayout(panAjouterVIP);
        panAjouterVIP.setLayout(panAjouterVIPLayout);
        panAjouterVIPLayout.setHorizontalGroup(
            panAjouterVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAjouterVIPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(informationsVIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panAjouterVIPLayout.setVerticalGroup(
            panAjouterVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAjouterVIPLayout.createSequentialGroup()
                .addGroup(panAjouterVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panAjouterVIPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(informationsVIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        panConsulterLesEvenements.addTab("ajouter un VIP", panAjouterVIP);

        panAjouterMariage.setBackground(new java.awt.Color(255, 255, 255));

        panAjoutMariage.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajouter un mariage"));

        lbSelectionVIP1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lbSelectionVIP1.setText("Sélectionner un VIP dans la liste");

        lbConjoint.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lbConjoint.setText("Sélectionner le/la conjoint/e");

        btnValiderMariage.setText("Valider");
        btnValiderMariage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderMariageActionPerformed(evt);
            }
        });

        btnAnnulerMariage.setText("Annuler");
        btnAnnulerMariage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerMariageActionPerformed(evt);
            }
        });

        tableConjoint.setModel(leModeleVIPL);
        tableConjoint.setRowHeight(19);
        tableConjoint.setSelectionBackground(new java.awt.Color(255, 204, 204));
        tableConjoint.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane6.setViewportView(tableConjoint);

        tableVIP1.setModel(leModeleVIPL);
        tableVIP1.setOpaque(false);
        tableVIP1.setRowHeight(19);
        tableVIP1.setSelectionBackground(new java.awt.Color(204, 255, 204));
        tableVIP1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableVIP1.setUpdateSelectionOnSort(false);
        jScrollPane7.setViewportView(tableVIP1);

        lbDateMariage.setText("Date du mariage");

        lbLieuMariage.setText("Lieu du mariage");

        btnActualiserVIPL.setText("Actualiser");
        btnActualiserVIPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualiserVIPLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panAjoutMariageLayout = new javax.swing.GroupLayout(panAjoutMariage);
        panAjoutMariage.setLayout(panAjoutMariageLayout);
        panAjoutMariageLayout.setHorizontalGroup(
            panAjoutMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAjoutMariageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panAjoutMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSelectionVIP1)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualiserVIPL))
                .addGap(46, 46, 46)
                .addGroup(panAjoutMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbConjoint)
                    .addGroup(panAjoutMariageLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(panAjoutMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panAjoutMariageLayout.createSequentialGroup()
                                .addComponent(btnValiderMariage)
                                .addGap(18, 18, 18)
                                .addComponent(btnAnnulerMariage))
                            .addComponent(lbLieuMariage)
                            .addComponent(lbDateMariage)
                            .addComponent(txtDateMariage)
                            .addComponent(txtLieuMariage))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        panAjoutMariageLayout.setVerticalGroup(
            panAjoutMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAjoutMariageLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panAjoutMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSelectionVIP1)
                    .addComponent(lbConjoint))
                .addGroup(panAjoutMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAjoutMariageLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panAjoutMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panAjoutMariageLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbDateMariage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDateMariage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lbLieuMariage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLieuMariage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panAjoutMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAjoutMariageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(panAjoutMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAnnulerMariage)
                            .addComponent(btnValiderMariage))
                        .addGap(29, 29, 29))
                    .addGroup(panAjoutMariageLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnActualiserVIPL)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout panAjouterMariageLayout = new javax.swing.GroupLayout(panAjouterMariage);
        panAjouterMariage.setLayout(panAjouterMariageLayout);
        panAjouterMariageLayout.setHorizontalGroup(
            panAjouterMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAjouterMariageLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(panAjoutMariage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        panAjouterMariageLayout.setVerticalGroup(
            panAjouterMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAjouterMariageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panAjoutMariage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panConsulterLesEvenements.addTab("ajouter un mariage", panAjouterMariage);

        panAjouterDivorce.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations du divorce"));

        tableMariages.setBackground(new java.awt.Color(204, 204, 204));
        tableMariages.setModel(leModeleMariage);
        tableMariages.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tableMariages);

        lbSelectionnerMariage.setText("Sélectionner un mariage dans la liste");

        btnValiderDivorce.setText("Valider");
        btnValiderDivorce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderDivorceActionPerformed(evt);
            }
        });

        btnAnnulerDivorce.setText("Annuler");

        jLabel1.setText("Date du divorce");

        txtDateDivorce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateDivorceActionPerformed(evt);
            }
        });

        btnActualiserMariages.setText("Actualiser");
        btnActualiserMariages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualiserMariagesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnActualiserMariages)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbSelectionnerMariage)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnValiderDivorce)
                                        .addGap(21, 21, 21)
                                        .addComponent(btnAnnulerDivorce))
                                    .addComponent(txtDateDivorce, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(99, 99, 99))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbSelectionnerMariage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtDateDivorce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnValiderDivorce)
                            .addComponent(btnAnnulerDivorce))))
                .addGap(18, 18, 18)
                .addComponent(btnActualiserMariages)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panAjouterDivorceLayout = new javax.swing.GroupLayout(panAjouterDivorce);
        panAjouterDivorce.setLayout(panAjouterDivorceLayout);
        panAjouterDivorceLayout.setHorizontalGroup(
            panAjouterDivorceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAjouterDivorceLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panAjouterDivorceLayout.setVerticalGroup(
            panAjouterDivorceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAjouterDivorceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panConsulterLesEvenements.addTab("ajouter un Divorce", panAjouterDivorce);

        panAjouterPhoto.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panAjouterPhotoLayout = new javax.swing.GroupLayout(panAjouterPhoto);
        panAjouterPhoto.setLayout(panAjouterPhotoLayout);
        panAjouterPhotoLayout.setHorizontalGroup(
            panAjouterPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );
        panAjouterPhotoLayout.setVerticalGroup(
            panAjouterPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        panConsulterLesEvenements.addTab("ajouter une photo", panAjouterPhoto);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane4.setBackground(java.awt.Color.white);

        jTable3.setModel(leModeleEvenementTotal);
        jScrollPane4.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panConsulterLesEvenements.addTab("consulter les événements", jPanel2);

        lbBienvenue.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        lbBienvenue.setText("Bienvenue");

        btnDeconnexion.setText("déconnexion");
        btnDeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeconnexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(lbBienvenue)
                .addGap(53, 53, 53)
                .addComponent(lbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeconnexion)
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panConsulterLesEvenements, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbBienvenue))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeconnexion)
                            .addComponent(lbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(panConsulterLesEvenements, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btValiderVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderVIPActionPerformed
        // TODO add your handling code here:
        try {
            // validation saisie du nom
            String leNom = txtNom.getText();
            if (leNom.isEmpty()) {
                throw new Exception("champ nom vide");
            }
            vip.setNom(leNom);

            // saisie du prénom
            String lePrenom = txtPrenom.getText();
            if (lePrenom.isEmpty()) {
                throw new Exception("champ prénom vide");
            }
            vip.setPrenom(lePrenom);

            // saisie de la civilité
            if (rdM.isSelected()) {
                vip.setCivilite(rdM.getText());
            } else {
                vip.setCivilite(rdMme.getText());
            }

            // saisie date de naissance
            String laDateNaissance = txtDateNaissance.getText();
            String[] champsDate = laDateNaissance.split("/");
            try {
                LocalDate dateNaissance = LocalDate.of(
                        Integer.parseInt(champsDate[2]),
                        Integer.parseInt(champsDate[1]),
                        Integer.parseInt(champsDate[0])
                );
                vip.setDatenaissance(dateNaissance);
            } catch (DateTimeException | NumberFormatException | ArrayIndexOutOfBoundsException ex) {
                throw new Exception("format de date incorrect");
            }

            // saisie lieu de naissance
            String leLieuNaissance = txtLieuNaissance.getText();
            if (leLieuNaissance.isEmpty()) {
                throw new Exception("champ lieu de naissance vide");
            }
            vip.setLieunaissance(leLieuNaissance);

            // saisie role
            if (chkActeur.isSelected() && chkRealisateur.isSelected()) {
                vip.setRole("AR");
            } else if (chkActeur.isSelected()) {
                vip.setRole("A");
            } else {
                vip.setRole("R");
            }

            // saisie statut
            if (rdLibre.isSelected()) {
                vip.setStatut("L");
            } else {
                vip.setStatut("O");
            }

            //saisie pays
            vip.setPays(listPays.getSelectedValue());
            
            // insertion dans la base
            leModeleVIP.insererVIP(vip);
            
            // réinitialisation des champs
            txtNom.setText("");
            txtPrenom.setText("");
            rdM.setSelected(true);
            rdMme.setSelected(false);
            txtDateNaissance.setText("");
            txtLieuNaissance.setText("");
            chkActeur.setSelected(false);
            chkRealisateur.setSelected(false);
            rdLibre.setSelected(true);
            rdOccupe.setSelected(false);
            listPays.setSelectedIndex(0);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btValiderVIPActionPerformed

    private void btAnnulerVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnnulerVIPActionPerformed
        // TODO add your handling code here:
        txtNom.setText("");
        txtPrenom.setText("");
        rdM.setSelected(true);
        rdMme.setSelected(false);
        txtDateNaissance.setText("");
        txtLieuNaissance.setText("");
        chkActeur.setSelected(false);
        chkRealisateur.setSelected(false);
        rdLibre.setSelected(true);
        rdOccupe.setSelected(false);
        listPays.setSelectedIndex(0);
    }//GEN-LAST:event_btAnnulerVIPActionPerformed

    private void btnDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeconnexionActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnDeconnexionActionPerformed

    private void btnValiderMariageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderMariageActionPerformed
        // TODO add your handling code here:
        // récupération de l'année d'aujourd'hui
        cal.setTime(date);
        int year = Integer.valueOf(String.format("%1$tY",date));
        
        try {
            //numVIP1
            int numVIP1 = (int) tableVIP1.getValueAt(tableVIP1.getSelectedRow(),0);
            evenement.setNumVIP1(numVIP1);
            
            //numVIP2
            int numConjoint = (int) tableConjoint.getValueAt(tableConjoint.getSelectedRow(),0);
            evenement.setNumVIP2(numConjoint);
            
            // date_mariage
            String laDateMariage = txtDateMariage.getText();
            if (laDateMariage.isEmpty()) {
                throw new Exception("date incorrecte");
            }
            else if (Integer.parseInt(laDateMariage)>year) {
                throw new Exception("date incorrecte");
            }
            evenement.setDate_mariage(Integer.parseInt(laDateMariage));
           
            //lieu_mariage
            String lieuMariage = txtLieuMariage.getText();
            if (lieuMariage.isEmpty()) {
                throw new Exception("champ lieu de mariage vide");
            }
            evenement.setLieu_mariage(lieuMariage);
                                  
            // insertion dans la base
            leModeleEvenement.insererEvenement(evenement);
            
            // réinitialisation des champs
            txtDateMariage.setText("");
            txtLieuMariage.setText("");
            tableVIP1.getSelectionModel().setSelectionInterval(0,0);
            tableConjoint.getSelectionModel().setSelectionInterval(0,0);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnValiderMariageActionPerformed

    private void btnAnnulerMariageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerMariageActionPerformed
        // TODO add your handling code here:
        txtDateMariage.setText("");
        txtLieuMariage.setText("");
        tableVIP1.getSelectionModel().setSelectionInterval(0,0);
        tableConjoint.getSelectionModel().setSelectionInterval(0,0);
    }//GEN-LAST:event_btnAnnulerMariageActionPerformed

    private void txtDateDivorceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateDivorceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateDivorceActionPerformed

    private void btnValiderDivorceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderDivorceActionPerformed
        // TODO add your handling code here:
        
        try {
            //numVIP1
            int numVIP1 = (int) tableMariages.getValueAt(tableMariages.getSelectedRow(),0);
            evenement.setNumVIP1(numVIP1);
            
            //date mariage
            
            int dateMariage = (int) tableMariages.getValueAt(tableMariages.getSelectedRow(),6);
            evenement.setDate_mariage(dateMariage);
            
            // date divorce
            String dateDivorce = txtDateDivorce.getText();
            if (dateDivorce.isEmpty()) {
                throw new Exception("date incorrecte");
            }
            int laDateDivorce = Integer.parseInt(txtDateDivorce.getText());
            evenement.setDate_divorce(laDateDivorce);
            
            System.out.println(numVIP1+" "+dateMariage+" "+dateDivorce);
                                  
            // insertion dans la base
            leModeleEvenement.modifierEvenement(evenement);
            
            // réinitialisation des champs
            txtDateDivorce.setText("");
            tableMariages.getSelectionModel().setSelectionInterval(0,0);
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnValiderDivorceActionPerformed

    private void btnActualiserMariagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualiserMariagesActionPerformed
        try {
            // TODO add your handling code here:
            leModeleMariage.chargerLesMariages();
        } catch (SQLException ex) {
            Logger.getLogger(AccueilApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualiserMariagesActionPerformed

    private void btnActualiserVIPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualiserVIPLActionPerformed
        try {
            // TODO add your handling code here:
            leModeleVIPL.chargerLesVIPL();
        } catch (SQLException ex) {
            Logger.getLogger(AccueilApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualiserVIPLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccueilApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccueilApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccueilApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccueilApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AccueilApplication().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AccueilApplication.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnnulerVIP;
    private javax.swing.JButton btValiderVIP;
    private javax.swing.JButton btnActualiserMariages;
    private javax.swing.JButton btnActualiserVIPL;
    private javax.swing.JToggleButton btnAnnulerDivorce;
    private javax.swing.JButton btnAnnulerMariage;
    private javax.swing.JButton btnDeconnexion;
    private javax.swing.JToggleButton btnValiderDivorce;
    private javax.swing.JButton btnValiderMariage;
    private javax.swing.ButtonGroup buttonGroupCivilite;
    private javax.swing.ButtonGroup buttonGroupRole;
    private javax.swing.ButtonGroup buttonGroupStatut;
    private javax.swing.JCheckBox chkActeur;
    private javax.swing.JCheckBox chkRealisateur;
    private javax.swing.JPanel informationsVIP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lbBienvenue;
    private javax.swing.JLabel lbCivilite;
    private javax.swing.JLabel lbConjoint;
    private javax.swing.JLabel lbDateMariage;
    private javax.swing.JLabel lbDateNaissance;
    private javax.swing.JLabel lbLieuMariage;
    private javax.swing.JLabel lbLieuNaissance;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbNom;
    private javax.swing.JLabel lbPays;
    private javax.swing.JLabel lbPrenom;
    private javax.swing.JLabel lbRole;
    private javax.swing.JLabel lbSelectionVIP1;
    private javax.swing.JLabel lbSelectionnerMariage;
    private javax.swing.JLabel lbStatut;
    private javax.swing.JList<String> listPays;
    private javax.swing.JPanel panAjoutMariage;
    private javax.swing.JPanel panAjouterDivorce;
    private javax.swing.JPanel panAjouterMariage;
    private javax.swing.JPanel panAjouterPhoto;
    private javax.swing.JPanel panAjouterVIP;
    private javax.swing.JTabbedPane panConsulterLesEvenements;
    private javax.swing.JRadioButton rdLibre;
    private javax.swing.JRadioButton rdM;
    private javax.swing.JRadioButton rdMme;
    private javax.swing.JRadioButton rdOccupe;
    private javax.swing.JTable tableConjoint;
    private javax.swing.JTable tableMariages;
    private javax.swing.JTable tableVIP1;
    private javax.swing.JTextField txtDateDivorce;
    private javax.swing.JTextField txtDateMariage;
    private javax.swing.JTextField txtDateNaissance;
    private javax.swing.JTextField txtLieuMariage;
    private javax.swing.JTextField txtLieuNaissance;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    // End of variables declaration//GEN-END:variables
}
