/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.sql.SQLException;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modele.ModeleJListPays;
import modele.ModeleJTableVIP;
import tables.VIP;

/**
 *
 * @author Alice
 */
public class AccueilApplication extends javax.swing.JFrame {

    private ModeleJTableVIP leModeleVIP;
    private ModeleJListPays leModelePays;
    private VIP vip = new VIP();
    //private boolean etatSortie;

    /**
     * Creates new form AccueilApplication
     */
    public AccueilApplication() throws SQLException {
        // instanciation du modèle de données de la JTable (liste des VIP)
        this.leModeleVIP = new ModeleJTableVIP();
        this.leModelePays = new ModeleJListPays();
        
        //etatSortie = false;
        
        
        
        try {
            leModeleVIP.chargerLesVIP();
            initComponents();
        } catch (SQLException ex) {
            System.out.println("Erreur au chargement : "+ex.getMessage());
        }
    }
    /*
    public boolean doModal() {
        setVisible(true);
        return etatSortie;
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCivilite = new javax.swing.ButtonGroup();
        buttonGroupRole = new javax.swing.ButtonGroup();
        buttonGroupStatut = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panAjouterVIP = new javax.swing.JPanel();
        informationsVIP = new javax.swing.JPanel();
        lbNom = new javax.swing.JLabel();
        lbPrenom = new javax.swing.JLabel();
        lbCivilite = new javax.swing.JLabel();
        lbDateNaissance = new javax.swing.JLabel();
        lbLieuNaissance = new javax.swing.JLabel();
        lbRole = new javax.swing.JLabel();
        lbStatut = new javax.swing.JLabel();
        lbPays = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        rdM = new javax.swing.JRadioButton();
        rdMme = new javax.swing.JRadioButton();
        txtDateNaissance = new javax.swing.JTextField();
        txtLieuNaissance = new javax.swing.JTextField();
        rdLibre = new javax.swing.JRadioButton();
        rdOccupe = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPays = new javax.swing.JList<>();
        btValiderVIP = new javax.swing.JButton();
        btAnnulerVIP = new javax.swing.JButton();
        chkActeur = new javax.swing.JCheckBox();
        chkRealisateur = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panAjouterMariage = new javax.swing.JPanel();
        panAjouterDivorce = new javax.swing.JPanel();
        panAjouterPhoto = new javax.swing.JPanel();
        lbBienvenue = new javax.swing.JLabel();
        lbLogin = new javax.swing.JLabel();
        btnDeconnexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        informationsVIP.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations VIP"));

        lbNom.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lbNom.setText("Nom");

        lbPrenom.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lbPrenom.setText("Prénom");

        lbCivilite.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lbCivilite.setText("Civilité");

        lbDateNaissance.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lbDateNaissance.setText("Date de naissance");

        lbLieuNaissance.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lbLieuNaissance.setText("Lieu de naissance");

        lbRole.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lbRole.setText("Role");

        lbStatut.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lbStatut.setText("Statut");

        lbPays.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        lbPays.setText("Pays");

        buttonGroupCivilite.add(rdM);
        rdM.setSelected(true);
        rdM.setText("M.");

        buttonGroupCivilite.add(rdMme);
        rdMme.setText("Mme");

        buttonGroupStatut.add(rdLibre);
        rdLibre.setSelected(true);
        rdLibre.setText("Libre");

        buttonGroupStatut.add(rdOccupe);
        rdOccupe.setText("Occupé");

        listPays.setModel(leModelePays);
        listPays.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listPays);

        btValiderVIP.setText("Valider");
        btValiderVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderVIPActionPerformed(evt);
            }
        });

        btAnnulerVIP.setText("Annuler");
        btAnnulerVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerVIPActionPerformed(evt);
            }
        });

        chkActeur.setText("Acteur/trice");

        chkRealisateur.setText("Réalisateur/trice");

        javax.swing.GroupLayout informationsVIPLayout = new javax.swing.GroupLayout(informationsVIP);
        informationsVIP.setLayout(informationsVIPLayout);
        informationsVIPLayout.setHorizontalGroup(
            informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationsVIPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRole)
                    .addComponent(lbNom)
                    .addComponent(lbPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCivilite)
                    .addComponent(lbDateNaissance)
                    .addComponent(lbLieuNaissance)
                    .addComponent(lbStatut)
                    .addComponent(lbPays)
                    .addComponent(btValiderVIP, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informationsVIPLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btAnnulerVIP)
                        .addContainerGap())
                    .addGroup(informationsVIPLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(informationsVIPLayout.createSequentialGroup()
                                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(informationsVIPLayout.createSequentialGroup()
                                        .addComponent(rdM, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdMme, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(informationsVIPLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLieuNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informationsVIPLayout.createSequentialGroup()
                                                .addComponent(rdOccupe)
                                                .addGap(44, 44, 44)))))
                                .addContainerGap(28, Short.MAX_VALUE))
                            .addGroup(informationsVIPLayout.createSequentialGroup()
                                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdLibre, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(informationsVIPLayout.createSequentialGroup()
                                        .addComponent(chkActeur)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkRealisateur)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        informationsVIPLayout.setVerticalGroup(
            informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationsVIPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNom)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrenom)
                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCivilite)
                    .addComponent(rdM)
                    .addComponent(rdMme))
                .addGap(5, 5, 5)
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDateNaissance)
                    .addComponent(txtDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLieuNaissance)
                    .addComponent(txtLieuNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRole)
                    .addComponent(chkActeur)
                    .addComponent(chkRealisateur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStatut)
                    .addComponent(rdLibre)
                    .addComponent(rdOccupe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPays)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(informationsVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btValiderVIP)
                    .addComponent(btAnnulerVIP))
                .addContainerGap())
        );

        jTable1.setModel(leModeleVIP);
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout panAjouterVIPLayout = new javax.swing.GroupLayout(panAjouterVIP);
        panAjouterVIP.setLayout(panAjouterVIPLayout);
        panAjouterVIPLayout.setHorizontalGroup(
            panAjouterVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAjouterVIPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(informationsVIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panAjouterVIPLayout.setVerticalGroup(
            panAjouterVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAjouterVIPLayout.createSequentialGroup()
                .addGroup(panAjouterVIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panAjouterVIPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(informationsVIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ajouter un VIP", panAjouterVIP);

        javax.swing.GroupLayout panAjouterMariageLayout = new javax.swing.GroupLayout(panAjouterMariage);
        panAjouterMariage.setLayout(panAjouterMariageLayout);
        panAjouterMariageLayout.setHorizontalGroup(
            panAjouterMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );
        panAjouterMariageLayout.setVerticalGroup(
            panAjouterMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ajouter un mariage", panAjouterMariage);

        javax.swing.GroupLayout panAjouterDivorceLayout = new javax.swing.GroupLayout(panAjouterDivorce);
        panAjouterDivorce.setLayout(panAjouterDivorceLayout);
        panAjouterDivorceLayout.setHorizontalGroup(
            panAjouterDivorceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );
        panAjouterDivorceLayout.setVerticalGroup(
            panAjouterDivorceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ajouter un Divorce", panAjouterDivorce);

        javax.swing.GroupLayout panAjouterPhotoLayout = new javax.swing.GroupLayout(panAjouterPhoto);
        panAjouterPhoto.setLayout(panAjouterPhotoLayout);
        panAjouterPhotoLayout.setHorizontalGroup(
            panAjouterPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );
        panAjouterPhotoLayout.setVerticalGroup(
            panAjouterPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ajouter une photo", panAjouterPhoto);

        lbBienvenue.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        lbBienvenue.setText("Bienvenue");

        btnDeconnexion.setText("déconnexion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(lbBienvenue)
                .addGap(53, 53, 53)
                .addComponent(lbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeconnexion)
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbBienvenue))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeconnexion)
                            .addComponent(lbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btValiderVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderVIPActionPerformed
        // TODO add your handling code here:
        try {
            // validation saisie du nom
            String leNom = txtNom.getText();
            if (leNom.isEmpty()) {
                throw new Exception("champ nom vide");
            }
           vip.setNom(leNom);
            
            // saisie du prénom
            String lePrenom = txtPrenom.getText();
            if (lePrenom.isEmpty()) {
                throw new Exception("champ prénom vide");
            }
            vip.setPrenom(lePrenom);
            
            // saisie de la civilité
            if (rdM.isSelected()) {
                vip.setCivilite(rdM.getText());
            }
            else {
                vip.setCivilite(rdMme.getText());
            }
            
            // saisie date de naissance
            String laDateNaissance = txtDateNaissance.getText();
            String[] champsDate = laDateNaissance.split("/");
            try {
                LocalDate dateNaissance = LocalDate.of(
                    Integer.parseInt(champsDate[2]),
                    Integer.parseInt(champsDate[1]),
                    Integer.parseInt(champsDate[0])
                );
                vip.setDatenaissance(dateNaissance);
            } catch (DateTimeException | NumberFormatException | ArrayIndexOutOfBoundsException ex) {
                throw new Exception("format de date incorrect");
            }
            
            // saisie lieu de naissance
            String leLieuNaissance = txtLieuNaissance.getText();
            if (leLieuNaissance.isEmpty()) {
                throw new Exception("champ lieu de naissance vide");
            }
            vip.setLieunaissance(leLieuNaissance);
            
            // saisie role
            if (chkActeur.isSelected() && chkRealisateur.isSelected()) {
                vip.setRole("AR");
            }
            else if (chkActeur.isSelected()) {
                vip.setRole("A");
            }
            else {
                vip.setRole("R");
            }
            
            // saisie statut
            if (rdLibre.isSelected()){
                vip.setStatut("L");
            }
            else {
                vip.setStatut("O");
            }
            
            //saisie pays
            vip.setPays(listPays.getSelectedValue());
            
            //etatSortie = true;
            
            leModeleVIP.insererVIP(vip);
            
           
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }
        System.out.println(vip.getDatenaissance());
        
    }//GEN-LAST:event_btValiderVIPActionPerformed

    private void btAnnulerVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnnulerVIPActionPerformed
        // TODO add your handling code here:
        txtNom.setText("");
        txtPrenom.setText("");
        rdM.setSelected(true);
        rdMme.setSelected(false);
        txtDateNaissance.setText("");
        txtLieuNaissance.setText("");
        chkActeur.setSelected(false);
        chkRealisateur.setSelected(false);
        rdLibre.setSelected(true);
        rdOccupe.setSelected(false);
        listPays.setSelectedIndex(0);
    }//GEN-LAST:event_btAnnulerVIPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccueilApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccueilApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccueilApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccueilApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AccueilApplication().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AccueilApplication.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnnulerVIP;
    private javax.swing.JButton btValiderVIP;
    private javax.swing.JButton btnDeconnexion;
    private javax.swing.ButtonGroup buttonGroupCivilite;
    private javax.swing.ButtonGroup buttonGroupRole;
    private javax.swing.ButtonGroup buttonGroupStatut;
    private javax.swing.JCheckBox chkActeur;
    private javax.swing.JCheckBox chkRealisateur;
    private javax.swing.JPanel informationsVIP;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbBienvenue;
    private javax.swing.JLabel lbCivilite;
    private javax.swing.JLabel lbDateNaissance;
    private javax.swing.JLabel lbLieuNaissance;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbNom;
    private javax.swing.JLabel lbPays;
    private javax.swing.JLabel lbPrenom;
    private javax.swing.JLabel lbRole;
    private javax.swing.JLabel lbStatut;
    private javax.swing.JList<String> listPays;
    private javax.swing.JPanel panAjouterDivorce;
    private javax.swing.JPanel panAjouterMariage;
    private javax.swing.JPanel panAjouterPhoto;
    private javax.swing.JPanel panAjouterVIP;
    private javax.swing.JRadioButton rdLibre;
    private javax.swing.JRadioButton rdM;
    private javax.swing.JRadioButton rdMme;
    private javax.swing.JRadioButton rdOccupe;
    private javax.swing.JTextField txtDateNaissance;
    private javax.swing.JTextField txtLieuNaissance;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    // End of variables declaration//GEN-END:variables
}
